import fs from 'fs'
import path from 'path'

/**
 * Script to compile all GraphQL schema files into a single file
 * This makes it easy to share the complete schema with frontend developers
 */

const SCHEMA_DIR = path.join(__dirname, '../src/graphql/schema')
const OUTPUT_FILE = path.join(SCHEMA_DIR, 'compiled-schema.graphql')

// Files to exclude from compilation
const EXCLUDE_FILES = ['compiled-schema.graphql']

// Order of files for better organization (optional)
const FILE_ORDER = [
  'schema.graphql',        // Root schema with Query/Mutation types
  'user.graphql',
  'leave-type.graphql',
  'leave-request.graphql',
  'leave-balance.graphql',
  'leave-batch.graphql',
  'leave-history.graphql',
  'holiday.graphql',
  'statistics.graphql',
  'hr-pending-approvals.graphql',
]

function compileSchema() {
  console.log('🔨 Compiling GraphQL schema files...\n')

  // Read all .graphql files in the schema directory
  const allFiles = fs
    .readdirSync(SCHEMA_DIR)
    .filter(file => file.endsWith('.graphql') && !EXCLUDE_FILES.includes(file))

  // Sort files according to FILE_ORDER, then alphabetically for any remaining files
  const sortedFiles = [
    ...FILE_ORDER.filter(file => allFiles.includes(file)),
    ...allFiles.filter(file => !FILE_ORDER.includes(file)).sort(),
  ]

  console.log('📄 Found schema files:')
  sortedFiles.forEach(file => console.log(`   - ${file}`))
  console.log()

  // Compile all schemas into one
  const compiledSchema = sortedFiles
    .map(file => {
      const filePath = path.join(SCHEMA_DIR, file)
      const content = fs.readFileSync(filePath, 'utf-8')
      
      return `# ============================================
# ${file}
# ============================================

${content}
`
    })
    .join('\n')

  // Add header with metadata
  const header = `# ============================================
# COMPILED GRAPHQL SCHEMA
# ============================================
# 
# This file is auto-generated by scripts/compile-schema.ts
# DO NOT EDIT THIS FILE MANUALLY
# 
# Generated: ${new Date().toISOString()}
# Source: src/graphql/schema/*.graphql
# 
# To regenerate this file, run:
#   npm run compile-schema
# 
# ============================================

`

  const finalSchema = header + compiledSchema

  // Write to output file
  fs.writeFileSync(OUTPUT_FILE, finalSchema, 'utf-8')

  console.log('✅ Schema compiled successfully!')
  console.log(`📦 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`)
  console.log(`📊 Total size: ${(finalSchema.length / 1024).toFixed(2)} KB`)
  console.log(`📝 Total lines: ${finalSchema.split('\n').length}`)
}

// Run the compilation
try {
  compileSchema()
} catch (error) {
  console.error('❌ Error compiling schema:', error)
  process.exit(1)
}
